//! The general data models and types used across the whole Aphanite service

use toasty::{Deferred, Model};
use uuid::Uuid;

/// A player account
///
/// This is used across Yggdrasil and Phenocryst.
#[derive(Debug, Clone, Model)]
pub struct User {
    /// The UUID of the User
    #[key]
    #[auto]
    pub id: Uuid,

    /// The nickname of the User
    pub nickname: String,

    /// The email of the User
    #[unique]
    pub email: String,

    /// PHC representation of Argon2 password hash & salt
    ///
    /// See [`PasswordHash`](argon2::PasswordHash) for details.
    pub password: String,

    /// Preferred language of this user
    pub preferred_language: String,

    /// Permissions of this user
    pub permission: u32,

    /// Instances that this user is allowed to play (Phenocryst only)
    #[has_many(via=instances_relation.instance)]
    pub instances: Deferred<Vec<Instance>>,

    /// Internal relationship constraint; should NOT be used
    #[has_many]
    instances_relation: Deferred<Vec<UserInstance>>,

    #[has_many(pair=owner)]
    pub profiles: Deferred<Vec<crate::service::yggdrasil::types::GameProfile>>,

    #[has_many]
    tokens: Deferred<Vec<Token>>,

    /// The TOTP secret of this user;
    ///
    /// The TOTP system can reduce the use of password, and is applied as 1FA here.
    /// This should be a very long and random string at least 128 bits (16 bytes).
    pub totp_secret: Option<String>,
    pub totp_active: bool,
}

/// Permission types of a user
///
/// This is stored in u32 bitflags. See the provided methods for how to interact with this type.
#[derive(Clone, Copy, strum_macros::EnumIter, Debug, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Permission {
    /// This user is allowed to Manage this Aphanite instance
    ///
    /// Bit: `0b1`
    Management,
}

impl Permission {
    /// Return a number with the corresponding bit set as 1
    fn as_u32(&self) -> u32 {
        match self {
            Self::Management => 0b1,
        }
    }

    /// Parse a set of flags from a u32 number
    pub fn from_u32(flags: u32) -> Vec<Self> {
        use strum::IntoEnumIterator;

        let mut result = Vec::new();
        for permission in Self::iter() {
            if flags & permission.as_u32() != 0 {
                result.push(permission);
            }
        }
        result
    }

    /// Construct a number from a set of [`Permission`](Self)s
    pub fn to_u32(flags: &[Self]) -> u32 {
        let mut result = 0;
        for perm in flags.iter() {
            result |= perm.as_u32();
        }
        result
    }
}

pub trait ToPermission {
    /// If the number has the corresponding bit set as 1, this returns true; otherwise false.
    fn contains(&self, permission: Permission) -> bool;
}
impl ToPermission for u32 {
    fn contains(&self, permission: Permission) -> bool {
        self & permission.as_u32() != 0
    }
}

/// User to Instance relationship maps
///
/// This is used to implement multiple-multiple relationships between two models and should NOT be used directly.
#[derive(Clone, Debug, Model)]
// `pub` here is not required but without it rustc would produce a warning :(
pub struct UserInstance {
    #[key]
    #[auto]
    id: Uuid,

    #[index]
    user_id: Uuid,

    #[belongs_to(key=user_id, references=id)]
    user: Deferred<User>,

    #[index]
    instance_id: Uuid,

    #[belongs_to(key=instance_id, references=id)]
    instance: Instance,
}

/// An modpack instance
///
/// This is used only in Phenocryst.
#[derive(Clone, Debug, Model)]
pub struct Instance {
    /// The ID of the instance
    #[key]
    #[auto]
    id: Uuid,

    /// Name of this instance
    name: String,

    /// Description of this instance
    description: String,

    /// Hash of the modpack file
    ///
    /// This should be a BLAKE3 hash in lowercase hex format.
    hash: String,

    /// File of the modpack
    file: Uuid,
}

/// A token used to authorize requests
///
/// A token MUST be related to a [`User`], and MAY be related to a [`GameProfile`](crate::service::yggdrasil::types::GameProfile).
#[derive(Clone, Debug, Model)]
pub struct Token {
    /// The access token of this Token
    ///
    /// An access token is a UUID that the Server allocated to the user.
    #[key]
    #[auto]
    pub access_token: Uuid,

    /// Internal field
    #[index]
    user_id: Uuid,

    /// The User this token belongs to
    #[belongs_to(key=user_id, references=id)]
    pub user: Deferred<User>,

    /// The client token of this Token
    ///
    /// A client token is a string generated by the client to distinct different clients of a user
    pub client_token: String,

    /// The creation time of this token
    #[auto]
    pub created_at: jiff::Timestamp,

    /// Internal field
    #[index]
    pub profile_id: Option<Uuid>,

    /// The Minecraft player profile this token is associated with
    #[belongs_to(key=profile_id, references=id)]
    pub profile: Deferred<Option<crate::service::yggdrasil::types::GameProfile>>,
}
